# Generated by Django 6.0.4 on 2026-04-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('idmovimento', models.AutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=50, verbose_name='Identificação Item')),
                ('data', models.DateField(verbose_name='Data')),
                ('ent_sai', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Ent./Saída')),
                ('origem', models.CharField(blank=True, choices=[('NF', 'NF Entrada'), ('PD', 'Pedido'), ('RQ', 'Requisição'), ('OS', 'Ordem de Serviço'), ('AJ', 'Ajuste Manual')], max_length=2, verbose_name='Origem')),
                ('idorigem', models.IntegerField(default=0, verbose_name='ID Origem')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('usuariologado', models.CharField(blank=True, max_length=50, verbose_name='Usuário')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'db_table': 'movitem',
                'ordering': ['-data', '-idmovimento'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('idnfentrada', models.AutoField(primary_key=True, serialize=False)),
                ('numeronf', models.IntegerField(verbose_name='Número NF')),
                ('serie', models.CharField(blank=True, max_length=5, verbose_name='Série')),
                ('chaveacesso', models.CharField(blank=True, max_length=50, verbose_name='Chave de Acesso')),
                ('dataemissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('dataentrada', models.DateField(blank=True, null=True, verbose_name='Data Entrada')),
                ('idtransporte', models.IntegerField(default=0, verbose_name='ID Transportadora')),
                ('tipofrete', models.CharField(choices=[('C', 'CIF - Por conta do emitente'), ('F', 'FOB - Por conta do destinatário'), ('S', 'Sem frete')], default='S', max_length=1, verbose_name='Tipo Frete')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('L', 'Lançada'), ('C', 'Cancelada')], default='A', max_length=1, verbose_name='Status')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qtd. Total')),
                ('valortotalitens', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Itens')),
                ('valorfrete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frete')),
                ('valoracrecimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Acréscimo')),
                ('valordesconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto')),
                ('valoripi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IPI')),
                ('valoricms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ICMS')),
                ('valortotalnf', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total NF')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('cfop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cfop', verbose_name='CFOP')),
                ('condicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.condicaopagamento', verbose_name='Condição Pgto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Fornecedor')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.metodo', verbose_name='Método Pgto')),
            ],
            options={
                'verbose_name': 'NF de Entrada',
                'verbose_name_plural': 'NFs de Entrada',
                'db_table': 'nfcompra',
                'ordering': ['-dataentrada', '-idnfentrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemNFEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade')),
                ('valorunitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unit.')),
                ('ipi', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='IPI %')),
                ('icms', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='ICMS %')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('cfop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cfop', verbose_name='CFOP')),
                ('nfentrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.notafiscalentrada', verbose_name='NF Entrada')),
            ],
            options={
                'verbose_name': 'Item da NF de Entrada',
                'verbose_name_plural': 'Itens da NF de Entrada',
                'db_table': 'itecompr',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('idrequisicao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('dataatendi', models.DateField(blank=True, null=True, verbose_name='Data Atendimento')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('P', 'Parcial'), ('F', 'Finalizada'), ('C', 'Cancelada')], default='A', max_length=1, verbose_name='Status')),
                ('origem', models.CharField(blank=True, max_length=20, verbose_name='Origem')),
                ('idorigem', models.IntegerField(default=0, verbose_name='ID Origem')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('cliforemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Cliente/Forn.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'db_table': 'requis',
                'ordering': ['-data', '-idrequisicao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade')),
                ('atendido', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Atendido')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Saldo')),
                ('idorigem', models.IntegerField(default=0, verbose_name='ID Origem')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.requisicao', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens da Requisição',
                'db_table': 'reqitem',
            },
        ),
    ]
