# Generated by Django 6.0.4 on 2026-04-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_empresa_cadastros'),
        ('core', '0006_empresa_perfilusuario_projeto'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição / Referência')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Finalizado'), ('X', 'Cancelado')], default='A', max_length=1, verbose_name='Status')),
                ('usuario', models.CharField(blank=True, max_length=50, verbose_name='Usuário')),
                ('datafinalizacao', models.DateField(blank=True, null=True, verbose_name='Data Finalização')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'db_table': 'inventario',
                'ordering': ['-data', '-idinventario'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação')),
                ('descricao_item', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('saldo_sistema', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Saldo Sistema')),
                ('saldo_fisico', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Saldo Físico')),
                ('diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Diferença')),
                ('ajustado', models.BooleanField(default=False, verbose_name='Ajustado')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario', verbose_name='Inventário')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item do Inventário',
                'verbose_name_plural': 'Itens do Inventário',
                'db_table': 'invitem',
                'ordering': ['identificacao'],
            },
        ),
    ]
