# Generated by Django 6.0.4 on 2026-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_movimentoestoque_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='origem',
            field=models.CharField(blank=True, choices=[('NF', 'NF de Entrada'), ('PD', 'Pedido'), ('RQ', 'Requisição'), ('OS', 'Ordem de Serviço'), ('AJ', 'Ajuste de Estoque')], max_length=2, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='status',
            field=models.CharField(choices=[('A', 'Em Digitação'), ('L', 'Lançada'), ('C', 'Cancelada')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
