# Generated by Django 6.0.4 on 2026-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefornecedor',
            name='valorreferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Referência'),
        ),
        migrations.AlterField(
            model_name='clientefornecedor',
            name='tipocliforemp',
            field=models.CharField(choices=[('C', 'Cliente'), ('F', 'Fornecedor'), ('V', 'Vendedor'), ('E', 'Empregado/Técnico')], default='C', max_length=1, verbose_name='Tipo'),
        ),
    ]
