# Generated by Django 6.0.4 on 2026-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_item_controla_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo_item',
            field=models.CharField(choices=[('S', 'Serviço'), ('P', 'Produto / Mercadoria'), ('M', 'Matéria-Prima')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='controla_estoque',
            field=models.BooleanField(default=False, help_text='Gera movimentos de estoque (entradas/saídas), participa de requisições e inventários.', verbose_name='Controla Estoque'),
        ),
    ]
