# Generated by Django 6.0.4 on 2026-04-13 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idbanco', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('convenio', models.CharField(blank=True, max_length=30, verbose_name='Convênio')),
                ('numeroboleto', models.IntegerField(default=0, verbose_name='Próx. Nº Boleto')),
                ('jurosmora', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Mora %')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cfop',
            fields=[
                ('idcfop', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOPs',
                'db_table': 'cfop',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('idcidade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('codibge', models.CharField(blank=True, max_length=10, verbose_name='Cód. IBGE')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.IntegerField(default=0)),
                ('idusuario', models.IntegerField(default=0)),
                ('idcidade', models.IntegerField(default=0)),
                ('idtipoitem', models.IntegerField(default=0)),
                ('idgrupo', models.IntegerField(default=0)),
                ('iditem', models.IntegerField(default=0)),
                ('idcondpag', models.IntegerField(default=0)),
                ('idtabela', models.IntegerField(default=0)),
                ('idtelvenda', models.IntegerField(default=0)),
                ('idpedido', models.IntegerField(default=0)),
                ('idmovitem', models.IntegerField(default=0)),
                ('idmovcaixa', models.IntegerField(default=0)),
                ('idcontarec', models.IntegerField(default=0)),
                ('idcontapag', models.IntegerField(default=0)),
                ('idappajuda', models.IntegerField(default=0)),
                ('idmetodo', models.IntegerField(default=0)),
                ('idportador', models.IntegerField(default=0)),
                ('idbanco', models.IntegerField(default=0)),
                ('idconta', models.IntegerField(default=0)),
                ('idsubconta', models.IntegerField(default=0)),
                ('idcliforemp', models.IntegerField(default=0)),
                ('idcheque', models.IntegerField(default=0)),
                ('idassroteiro', models.IntegerField(default=0)),
                ('codigo_conv', models.IntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('idopercard', models.IntegerField(default=0)),
                ('idacertocomiss', models.IntegerField(default=0)),
                ('idmovimento', models.IntegerField(default=0)),
                ('idrequisicao', models.IntegerField(default=0)),
                ('idnfentrada', models.IntegerField(default=0)),
                ('idreneg', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Controle de Sequências',
                'db_table': 'controle',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('razao', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, verbose_name='Insc. Estadual')),
                ('fone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('foneass', models.CharField(blank=True, max_length=20, verbose_name='Fone Assistência')),
                ('fonewhats', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
                ('cor_cad', models.IntegerField(default=0, verbose_name='Cor Cadastro')),
                ('cor_adm', models.IntegerField(default=0, verbose_name='Cor Admin')),
                ('cor_tel', models.IntegerField(default=0, verbose_name='Cor TeleVendas')),
                ('cor_fin', models.IntegerField(default=0, verbose_name='Cor Financeiro')),
                ('cor_est', models.IntegerField(default=0, verbose_name='Cor Estoque')),
                ('set_baixadireta', models.BooleanField(default=False, verbose_name='Baixa Direta')),
                ('set_baixafat', models.BooleanField(default=False, verbose_name='Baixa Faturamento')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_adm', models.IntegerField(default=0, verbose_name='Nível Admin')),
                ('idvendedor', models.IntegerField(default=0, verbose_name='ID Vendedor')),
                ('ultimo_acesso', models.DateField(blank=True, null=True, verbose_name='Último Acesso')),
                ('ultimo_hora', models.CharField(blank=True, max_length=8, verbose_name='Última Hora')),
                ('ultimo_modulo', models.CharField(blank=True, max_length=30, verbose_name='Último Módulo')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
                ('acesso_cadastro', models.BooleanField(default=False, verbose_name='Cadastro')),
                ('acesso_administrativo', models.BooleanField(default=False, verbose_name='Administrativo')),
                ('acesso_televendas', models.BooleanField(default=False, verbose_name='TeleVendas')),
                ('acesso_financeiro', models.BooleanField(default=False, verbose_name='Financeiro')),
                ('acesso_estoque', models.BooleanField(default=False, verbose_name='Estoque')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'perfil_usuario',
            },
        ),
    ]
