# Generated by Django 6.0.4 on 2026-04-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
        ('financeiro', '0002_contarec_status_renegociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_entrada', models.CharField(default='RECEBIMENTO', max_length=100, verbose_name='Descrição Entrada')),
                ('desc_saida', models.CharField(default='PAGAMENTO', max_length=100, verbose_name='Descrição Saída')),
                ('desc_sangria', models.CharField(default='SANGRIA DE CAIXA', max_length=100, verbose_name='Descrição Sangria')),
                ('desc_suprimento', models.CharField(default='SUPRIMENTO DE CAIXA', max_length=100, verbose_name='Descrição Suprimento')),
                ('banco_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.banco', verbose_name='Banco Padrão')),
                ('conta_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.planoconta', verbose_name='Conta Caixa')),
                ('portador_cartao_cred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Cartão Crédito')),
                ('portador_cartao_deb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Cartão Débito')),
                ('portador_cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Cheque')),
                ('portador_dinheiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Dinheiro')),
                ('portador_pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador PIX / Transferência')),
                ('subconta_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.subconta', verbose_name='Sub-Conta Caixa')),
            ],
            options={
                'verbose_name': 'Configuração de Caixa',
                'verbose_name_plural': 'Configurações de Caixa',
                'db_table': 'cfgcaixa',
            },
        ),
    ]
