# Generated by Django 6.0.4 on 2026-04-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0002_cfgcaixa'),
        ('financeiro', '0002_contarec_status_renegociado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaocaixa',
            name='conta_caixa',
        ),
        migrations.RemoveField(
            model_name='configuracaocaixa',
            name='subconta_caixa',
        ),
        migrations.AddField(
            model_name='configuracaocaixa',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.planoconta', verbose_name='Conta Pagamento'),
        ),
        migrations.AddField(
            model_name='configuracaocaixa',
            name='conta_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.planoconta', verbose_name='Conta Recebimento'),
        ),
        migrations.AddField(
            model_name='configuracaocaixa',
            name='portador_sangria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Sangria (Cofre)'),
        ),
        migrations.AddField(
            model_name='configuracaocaixa',
            name='subconta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.subconta', verbose_name='Sub-Conta Pagamento'),
        ),
        migrations.AddField(
            model_name='configuracaocaixa',
            name='subconta_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financeiro.subconta', verbose_name='Sub-Conta Recebimento'),
        ),
        migrations.AlterField(
            model_name='configuracaocaixa',
            name='portador_cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.portador', verbose_name='Portador Cheques'),
        ),
    ]
