# Generated by Django 6.0.4 on 2026-04-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cfgcaixa_revisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('dataencerramento', models.DateField(blank=True, null=True, verbose_name='Data Encerramento')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
                'ordering': ['codigo'],
            },
        ),
    ]
