# Generated by Django 6.0.4 on 2026-04-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projeto'),
        ('financeiro', '0004_movcaixa_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoOrcamento',
            fields=[
                ('idorcamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Estimado')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta', verbose_name='Conta')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Orçamento do Projeto',
                'db_table': 'projeto_orcamento',
                'ordering': ['conta__deb_cred', 'conta__descrigrupo', 'conta__descricao'],
                'unique_together': {('projeto', 'conta')},
            },
        ),
    ]
