# Generated by Django 6.0.4 on 2026-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_perfilusuario_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='maps_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Google Maps API Key'),
        ),
    ]
