# Generated by Django 6.0.4 on 2026-05-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_maps_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='senha_expiry_days',
            field=models.IntegerField(default=0, help_text='0 = nunca expira', verbose_name='Expiração de Senha (dias)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password_changed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Última Troca de Senha'),
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.TextField(blank=True, verbose_name='Chave de Licença')),
                ('valid_from', models.DateField(verbose_name='Válida de')),
                ('valid_until', models.DateField(verbose_name='Válida até')),
                ('max_usuarios', models.IntegerField(default=5, verbose_name='Máx. Usuários')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenca', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'db_table': 'licencas',
                'ordering': ['empresa__razao'],
            },
        ),
    ]
