# Generated by Django 6.0.4 on 2026-05-07 13:20

import django.db.models.deletion
from django.db import migrations, models


def associar_empresa_existente(apps, schema_editor):
    """Associa o registro singleton (pk=1) à empresa pk=1, se ambos existirem."""
    CfgCaixa = apps.get_model('core', 'ConfiguracaoCaixa')
    Empresa = apps.get_model('core', 'Empresa')
    cfg = CfgCaixa.objects.filter(pk=1, empresa__isnull=True).first()
    if cfg:
        emp = Empresa.objects.filter(pk=1).first()
        if emp:
            cfg.empresa = emp
            cfg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_senha_expiry_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocaixa',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfg_caixa', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.RunPython(associar_empresa_existente, migrations.RunPython.noop),
    ]
