# Generated by Django 6.0.4 on 2026-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresa_cfgcaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='apelido',
            field=models.CharField(blank=True, max_length=60, verbose_name='Apelido'),
        ),
    ]
