# Generated by Django 6.0.4 on 2026-05-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código OS')),
                ('roteiro_id', models.IntegerField(blank=True, null=True, verbose_name='ID Roteiro')),
                ('origem', models.CharField(choices=[('OS', 'Ordem de Serviço'), ('OP', 'Ordem de Produção'), ('API', 'Integração API'), ('AVULSO', 'Avulso')], default='OS', max_length=10)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('A_CAMINHO', 'A Caminho'), ('EM_EXECUCAO', 'Em Execução'), ('PAUSADO', 'Pausado'), ('CONCLUIDO', 'Concluído'), ('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('tipo_atividade', models.CharField(max_length=100, verbose_name='Tipo de Atividade')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('ativo', models.CharField(blank=True, max_length=200, verbose_name='Ativo/Equipamento')),
                ('descricao', models.TextField(blank=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['prioridade', 'data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='ServApontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBSERVACAO', 'Observação'), ('EVIDENCIA', 'Evidência'), ('CHECKLIST', 'Checklist'), ('MEDICAO', 'Medição')], max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='campo/evidencias/')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='campo.servico')),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
                'ordering': ['registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ServMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_codigo', models.CharField(max_length=50)),
                ('item_descricao', models.CharField(max_length=200)),
                ('quantidade_prevista', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_realizada', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('REQUISICAO', 'Requisição'), ('AVULSO', 'Avulso')], default='REQUISICAO', max_length=15)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='campo.servico')),
            ],
            options={
                'verbose_name': 'Material do Serviço',
                'verbose_name_plural': 'Materiais do Serviço',
            },
        ),
        migrations.CreateModel(
            name='ServTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.IntegerField(blank=True, null=True, verbose_name='ID CRM')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('origem', models.CharField(choices=[('NATIVO', 'Usuário Nativo'), ('CRM', 'Técnico CRM')], default='NATIVO', max_length=10)),
                ('papel', models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('APOIO', 'Apoio')], default='RESPONSAVEL', max_length=15)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='campo.servico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
            ],
            options={
                'verbose_name': 'Técnico do Serviço',
                'verbose_name_plural': 'Técnicos do Serviço',
            },
        ),
        migrations.CreateModel(
            name='ServTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('AGENDADO', 'Agendado'), ('A_CAMINHO', 'A Caminho'), ('INICIO', 'Início'), ('PAUSA', 'Pausa'), ('RETOMADA', 'Retomada'), ('INTERVALO', 'Intervalo'), ('FIM', 'Fim'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('timestamp', models.DateTimeField()),
                ('data_ref', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempos', to='campo.servico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tempo de Serviço',
                'verbose_name_plural': 'Tempos de Serviço',
                'ordering': ['timestamp'],
            },
        ),
    ]
