# Generated by Django 6.0.4 on 2026-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servmaterial',
            name='item_codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servmaterial',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
