# Generated by Django 6.0.4 on 2026-05-25 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_fix_servmaterial_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servtempo',
            name='data_ref',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servtempo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
