# Generated by Django 6.0.4 on 2026-05-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_fix_servtempo_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('corpo', models.TextField(verbose_name='Corpo da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Script de Mensagem',
                'verbose_name_plural': 'Scripts de Mensagem',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
