# Generated by Django 6.0.4 on 2026-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='tipo_item',
            field=models.CharField(blank=True, max_length=1, verbose_name='Tipo Item'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_faturamento',
            field=models.CharField(blank=True, choices=[('U', 'Único'), ('S', 'Serviço'), ('M', 'Material')], default='U', max_length=1, verbose_name='Tipo Faturamento'),
        ),
    ]
