# Generated by Django 6.0.4 on 2026-04-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('B', 'Baixado'), ('P', 'Parcial'), ('C', 'Cancelado'), ('R', 'Renegociado')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
