# Generated by Django 6.0.4 on 2026-04-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projeto'),
        ('financeiro', '0003_aberturacaixa_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projeto', verbose_name='Projeto'),
        ),
    ]
