# Generated by Django 6.0.4 on 2026-04-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('idassroteiro', models.AutoField(primary_key=True, serialize=False)),
                ('dateemissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Execução'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Status')),
                ('qtdassistencias', models.IntegerField(default=0, verbose_name='Qtd. Assistências')),
                ('qtde_matutino', models.IntegerField(default=0, verbose_name='Qtd. Matutino')),
                ('qtde_vespertino', models.IntegerField(default=0, verbose_name='Qtd. Vespertino')),
                ('requisicaook', models.BooleanField(default=False, verbose_name='Requisição OK')),
                ('destino', models.CharField(blank=True, max_length=100, verbose_name='Destino')),
                ('idrequisicao', models.IntegerField(default=0, verbose_name='ID Requisição')),
                ('cliforemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Responsável')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Roteiro de Assistência',
                'verbose_name_plural': 'Roteiros de Assistência',
                'db_table': 'assrot',
                'ordering': ['-dateemissao', '-idassroteiro'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=1, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Original')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Multa %')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros %')),
                ('mesesatraso', models.IntegerField(default=0, verbose_name='Meses Atraso')),
                ('valormulta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Multa')),
                ('valorjuros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Juros')),
                ('valoratualizado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atualizado')),
                ('metodo', models.CharField(blank=True, max_length=20, verbose_name='Método Pgto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('contarec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contareceber', verbose_name='Conta a Receber')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranças', to='servicos.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Cobrança do Roteiro',
                'verbose_name_plural': 'Cobranças do Roteiro',
                'db_table': 'assrotcb',
            },
        ),
        migrations.CreateModel(
            name='BoletoRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=1, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('contarec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contareceber', verbose_name='Conta a Receber')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='servicos.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Boleto do Roteiro',
                'verbose_name_plural': 'Boletos do Roteiro',
                'db_table': 'assrotbl',
            },
        ),
        migrations.CreateModel(
            name='TecnicoRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_capacidade', models.IntegerField(default=0, verbose_name='Cap. Matutino')),
                ('ves_capacidade', models.IntegerField(default=0, verbose_name='Cap. Vespertino')),
                ('destino', models.CharField(blank=True, max_length=100, verbose_name='Destino')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='servicos.roteiro', verbose_name='Roteiro')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico do Roteiro',
                'verbose_name_plural': 'Técnicos do Roteiro',
                'db_table': 'assrott',
            },
        ),
        migrations.CreateModel(
            name='TeleVenda',
            fields=[
                ('idtelvenda', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('dataemissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('dataprevisao', models.DateField(blank=True, null=True, verbose_name='Data Previsão')),
                ('datainstal', models.DateField(blank=True, null=True, verbose_name='Data Realização')),
                ('datahora', models.CharField(blank=True, max_length=20, verbose_name='Data/Hora')),
                ('idvendrepre', models.IntegerField(default=0, verbose_name='ID Vendedor/Rep.')),
                ('idtecnico', models.IntegerField(default=0, verbose_name='ID Técnico')),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('R', 'Realizada'), ('C', 'Cancelada'), ('P', 'Pendente'), ('F', 'Faturada')], default='A', max_length=1, verbose_name='Status')),
                ('motivocancel', models.CharField(blank=True, max_length=200, verbose_name='Motivo Cancelamento')),
                ('quantidadetotal', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qtd. Total')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('atend_periodo', models.CharField(blank=True, choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('I', 'Integral')], max_length=1, verbose_name='Período Atend.')),
                ('atend_hora', models.CharField(blank=True, max_length=8, verbose_name='Hora Atend.')),
                ('atend_obs', models.TextField(blank=True, verbose_name='Obs. Atendimento')),
                ('impresso', models.BooleanField(default=False, verbose_name='Impresso')),
                ('idusuario', models.IntegerField(default=0, verbose_name='ID Usuário')),
                ('usuariolanc', models.CharField(blank=True, max_length=50, verbose_name='Usuário Lançamento')),
                ('marca', models.CharField(blank=True, max_length=20, verbose_name='Marca')),
                ('idusumarca', models.IntegerField(default=0, verbose_name='ID Usu. Marca')),
                ('idassroteiro', models.IntegerField(default=0, verbose_name='ID Roteiro')),
                ('equipe', models.IntegerField(default=0, verbose_name='Equipe')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='televendas', to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('condicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.condicaopagamento', verbose_name='Condição Pgto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.metodo', verbose_name='Método Pgto')),
                ('tabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tabelapreco', verbose_name='Tabela de Preço')),
            ],
            options={
                'verbose_name': 'TeleVenda / OS',
                'verbose_name_plural': 'TeleVendas / OS',
                'db_table': 'telvenda',
                'ordering': ['-dataprevisao', '-idtelvenda'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaTeleVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('telvenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='servicos.televenda', verbose_name='TeleVenda')),
            ],
            options={
                'verbose_name': 'Parcela da TeleVenda',
                'verbose_name_plural': 'Parcelas da TeleVenda',
                'db_table': 'parctel',
                'ordering': ['telvenda', 'parcela'],
            },
        ),
        migrations.CreateModel(
            name='OSRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execucao', models.CharField(blank=True, max_length=1, verbose_name='Execução')),
                ('recebimento', models.CharField(blank=True, max_length=1, verbose_name='Recebimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='servicos.roteiro', verbose_name='Roteiro')),
                ('telvenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.televenda', verbose_name='OS / TeleVenda')),
            ],
            options={
                'verbose_name': 'OS do Roteiro',
                'verbose_name_plural': 'OSs do Roteiro',
                'db_table': 'assrotos',
            },
        ),
        migrations.CreateModel(
            name='ItemTeleVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade')),
                ('valorunitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unit.')),
                ('instalacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Instalação')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('pagamentoav', models.CharField(blank=True, max_length=1, verbose_name='Pgto Antecipado')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.item', verbose_name='Item')),
                ('telvenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='servicos.televenda', verbose_name='TeleVenda')),
            ],
            options={
                'verbose_name': 'Item da TeleVenda',
                'verbose_name_plural': 'Itens da TeleVenda',
                'db_table': 'itemtel',
            },
        ),
    ]
