# Generated by Django 6.0.4 on 2026-04-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0003_cfgcaixa_revisao'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacontato', models.DateField(verbose_name='Data Contato')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('proximocontato', models.DateField(blank=True, null=True, verbose_name='Próximo Contato')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('usuario', models.CharField(blank=True, max_length=50, verbose_name='Usuário')),
                ('cliforemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='cadastros.clientefornecedor', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'clicalls',
                'ordering': ['-datacontato', '-id'],
            },
        ),
    ]
