# Generated by Django 6.0.4 on 2026-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_contatocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='televenda',
            name='idpedido',
            field=models.IntegerField(default=0, verbose_name='ID Pedido'),
        ),
    ]
