# Generated by Django 6.0.4 on 2026-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_televenda_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtelevenda',
            name='servico_pai',
            field=models.IntegerField(default=0, verbose_name='ID Serviço Pai'),
        ),
        migrations.AddField(
            model_name='itemtelevenda',
            name='tipo_item',
            field=models.CharField(blank=True, max_length=1, verbose_name='Tipo Item'),
        ),
        migrations.AddField(
            model_name='televenda',
            name='idpedido_material',
            field=models.IntegerField(default=0, verbose_name='ID Pedido Material'),
        ),
    ]
